### ISSUE TITLE
请问是否可以在微信上收到消息的提醒？

### ISSUE THREAD

**Issue by zzm88** [saucer-man/wepush#1]
按照说明成功发送了消息，但只能在**企业微信** app上面收到消息，是否可以在**普通微信**上面收到消息？

**Comment by saucer-man** [comment]
可以，参考https://sct.ftqq.com/forward第四步：

进入「我的企业」 → 「微信插件」，拉到下边扫描二维码，关注以后即可收到推送的消息。

![image](https://user-images.githubusercontent.com/32133080/134839990-4c975cc3-8ca4-4e15-9c2b-240a5c553e35.png)

**Comment by zzm88** [comment]
哇。。。感谢大佬秒回！！
补充一下，关注后，在企业消息列表页面，右上角点 **+ 号**，选择**接收企业消息**。
