### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by huoshenw** [saucer-man/wepush#2]
在执行docker-compose build && docker-compose up -d的时候返回

Building wepush
Sending build context to Docker daemon  487.9kB
Step 1/9 : FROM golang:1.16.4-alpine3.13 AS builder
 ---> cd061e3733f3
Step 2/9 : WORKDIR /src/wepush
 ---> Using cache
 ---> 61459517bc34
Step 3/9 : ENV GOPROXY="https://goproxy.cn"
 ---> Using cache
 ---> 106ed6ca5266
Step 4/9 : COPY src .
 ---> Using cache
 ---> ddf3e116cf97
Step 5/9 : RUN go build -ldflags '-w -s' -o wepush
 ---> Running in 6bce3b1e371d
go: github.com/antonfisher/nested-logrus-formatter@v1.3.1: Get "https://goproxy.cn/github.com/antonfisher/nested-logrus-formatter/@v/v1.3.1.mod": dial tcp 117.25.133.174:443: connect: connection refused
The command '/bin/sh -c go build -ldflags '-w -s' -o wepush' returned a non-zero code: 1
ERROR: Service 'wepush' failed to build : Build failed

我是想部署在路由器的docker上 发现即时挂了代理也连不上这个IP 请问有解决办法吗

**Comment by saucer-man** [comment]
1. 看起来还是代理的问题，尝试解决代理的问题2
2.  还可以抛弃docker编译，直接编译成二进制文件传上去运行。（在二进制文件同级目录下新建个wepush.env文件）
